apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-eks-cluster
  region: us-east-1

iam:
  serviceRoleARN: arn:aws:iam::746851085552:role/LabRole

managedNodeGroups:
  - name: nodegroup
    desiredCapacity: 2
    instanceType: t3.small
    ssh:
      enableSsm: true
    iam:
      instanceRoleARN: arn:aws:iam::746851085552:role/LabRole 